require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

target 'PairLunchPicker' do
    config = use_native_modules!

    use_react_native!(
        :path => config[:reactNativePath],
        :hermes_enabled => false # Disables Hermes
    )


    target 'PairLunchPickerTests' do
        inherit! :complete
        # Pods for testing
    end

    # Note: Disable if using use_frameworks!
    # use_flipper!() # Uncomment to enable Flipper

    post_install do |installer|
        react_native_post_install(installer)
    end
end
