export const atomic_people = [
  'Ryan Abel',
  'Molly Alger',
  'Micah Alles',
  'Patrick Bacon',
  'Jonah Bailey',
  'Mattie Behrens',
  'Rob Bell',
  'Louie Berwanger',
  'Kasey Bohn',
  'Sarah Brockett',
  'Rebecca Canterbury',
  'Jimmy Cerone',
  'Jonathon Chaffer',
  'Wonyoung Choi',
  'Joe Chrysler',
  'Drew Colthorp',
  'Noah Cooper',
  'Kimberly Crawford',
  'Shawn Crowley',
  'Lydia Cupery',
  'Kelly Daniels',
  'Kaitlin Diemer',
  'Kory Dondzila',
  'Grace Du Mez',
  'Lauren Ebels',
  'Bryan Elkus',
  'Victoria Elliott',
  'Carl Erickson',
  'Elaine Ezekiel',
  'Casey Falkowski',
  'Jing Fan',
  'Chris Farber',
  'John Fisher',
  'Justin Fitins',
  'Matt Fletcher',
  'Nate Gittlen',
  'Dylan Goings',
  'Stephen Guyton',
  'Kendra Haan',
  'Kyle Harris',
  'Nick Hazekamp',
  'Jesse Hill',
  'Brittany Hunter',
  'Justin Interino',
  'Allen Janyska',
  'Zachary Johnson',
  'Dan Kelch',
  'Nicholas Keuning',
  'Phil Kirkham',
  'Michael Li',
  'Meredith Lind',
  'Danielle Marsiglia',
  'Mike Marsiglia',
  'Brian May',
  'Rachael McQuater',
  'Adam Medema',
  'Lina Miller',
  'Anjali Munasinghe',
  'Jordan Nelson',
  "Mary O'Neill",
  'Patrick Pale',
  'Nathan Papes',
  'Tammy Pearson',
  'Andy Peterson',
  'Jason Porritt',
  'Viviana Rosas Romero',
  'John Ruble',
  'Jordan Schaenzle',
  'Sivhaun Sera',
  'Doug Shipp',
  'Jake Silas',
  'Matt Soto',
  'Ty Swanson',
  'Michael Swieton',
  'Sam Tahiri',
  'Taylor Vanden Hoek',
  'Gage Vander Clay',
  'Brian Vanderwal',
  'Terri Vruggink',
  'Patrick Warren',
  'Jeff Williams',
  'Alex Zurek',
];

export const atomic_people_urls = [
  {
    'Ryan Abel': require('../../images/atom_portraits/Abel-Ryan.jpg'),
    'Molly Alger': require('../../images/atom_portraits/Alger-Molly.jpg'),
    'Micah Alles': require('../../images/atom_portraits/Alles-Micah.jpg'),
    'Patrick Bacon': require('../../images/atom_portraits/Bacon-Patrick.jpg'),
    'Jonah Bailey': require('../../images/atom_portraits/Bailey-Jonah.jpg'),
    'Mattie Behrens': require('../../images/atom_portraits/Behrens-Mattie.jpg'),
    'Rob Bell': require('../../images/atom_portraits/Bell-Rob.jpg'),
    'Louie Berwanger': require('../../images/atom_portraits/Berwanger-Louie.jpg'),
    'Kasey Bohn': require('../../images/atom_portraits/Bohn-Kasey.jpg'),
    'Sarah Brockett': require('../../images/atom_portraits/Brockett-Sarah.jpg'),
    'Rebecca Canterbury': require('../../images/atom_portraits/Canterbury-Rebecca.jpg'),
    'Jimmy Cerone': require('../../images/atom_portraits/Cerone-Jimmy.jpg'),
    'Jonathan Chaffer': require('../../images/atom_portraits/Chaffer-Jonathan.jpg'),
    'Wonyoung Choi': require('../../images/atom_portraits/Choi-Wonyoung.jpg'),
    'Joe Chrysler': require('../../images/atom_portraits/Chrysler-Joe.jpg'),
    'Drew Colthorp': require('../../images/atom_portraits/Colthorp-Drew.jpg'),
    'Noah Cooper': require('../../images/atom_portraits/Cooper-Noah.jpg'),
    'Kimberly Crawford': require('../../images/atom_portraits/Crawford-Kim.jpg'),
    'Shawn Crowley': require('../../images/atom_portraits/Crowley-Shawn.jpg'),
    'Lydia Cupery': require('../../images/atom_portraits/Cupery-Lydia.jpg'),
    'Kelly Daniels': require('../../images/atom_portraits/Daniels-Kelly.jpg'),
    'Kaitlin Diemer': require('../../images/atom_portraits/Diemer-Kaitlin.jpg'),
    'Kory Dondzila': require('../../images/atom_portraits/Dondzila-Kory.jpg'),
    'Grace Du Mez': require('../../images/atom_portraits/DuMez-Grace.jpg'),
    'Lauren Ebels': require('../../images/atom_portraits/Ebels-Lauren.jpg'),
    'Bryan Elkus': require('../../images/atom_portraits/Elkus-Bryan.jpg'),
    'Victoria Elliott': require('../../images/no-image.jpeg'),
    'Carl Erickson': require('../../images/atom_portraits/Erickson-Carl.jpg'),
    'Elaine Ezekiel': require('../../images/atom_portraits/Ezekiel-Elaine.jpg'),
    'Casey Falkowski': require('../../images/atom_portraits/Falkowski-Casey.jpg'),
    'Jing Fan': require('../../images/atom_portraits/Fan-Jing.jpg'),
    'Chris Farber': require('../../images/atom_portraits/Farber-Chris.jpg'),
    'John Fisher': require('../../images/atom_portraits/Fisher-John.jpg'),
    'Justin Fitins': require('../../images/atom_portraits/Fitins-Justin.jpg'),
    'Matt Fletcher': require('../../images/atom_portraits/Fletcher-Matt.jpg'),
    'Nate Gittlen': require('../../images/atom_portraits/Gittlen-Nate.jpg'),
    'Dylan Goings': require('../../images/atom_portraits/Goings-Dylan.jpg'),
    'Stephen Guyton': require('../../images/atom_portraits/Guyton-Stephen.jpg'),
    'Kendra Haan': require('../../images/atom_portraits/Haan-Kendra.jpg'),
    'Kyle Harris': require('../../images/atom_portraits/Harris-Kyle.jpg'),
    'Nick Hazekamp': require('../../images/atom_portraits/Hazekamp-Nick.jpg'),
    'Jesse Hill': require('../../images/atom_portraits/Hill-Jesse.jpg'),
    'Brittany Hunter': require('../../images/atom_portraits/Hunter-Brittany.jpg'),
    'Justin Interino': require('../../images/atom_portraits/Interino-Justin.jpg'),
    'Allen Janyska': require('../../images/atom_portraits/Janyska-Allen.jpg'),
    'Zachary Johnson': require('../../images/atom_portraits/Johnson-Zachary.jpg'),
    'Dan Kelch': require('../../images/atom_portraits/Kelch-Dan.jpg'),
    'Nicholas Keuning': require('../../images/atom_portraits/Keuning-Nick.jpg'),
    'Phil Kirkham': require('../../images/atom_portraits/Kirkham-Phil.jpg'),
    'Michael Li': require('../../images/atom_portraits/Li-Michael.jpg'),
    'Meredith Lind': require('../../images/atom_portraits/Lind-Meredith.jpg'),
    'Danielle Marsiglia': require('../../images/atom_portraits/Marsiglia-Danielle.jpg'),
    'Mike Marsiglia': require('../../images/atom_portraits/Marsiglia-Mike.jpg'),
    'Brian May': require('../../images/atom_portraits/May-Brian.jpg'),
    'Rachael McQuater': require('../../images/atom_portraits/McQuater-Rachael.jpg'),
    'Adam Medema': require('../../images/atom_portraits/Medema-Adam.jpg'),
    'Lina Miller': require('../../images/atom_portraits/Miller-Lina.jpg'),
    'Anjali Munasinghe': require('../../images/atom_portraits/Munasinghe-Anjali.jpg'),
    'Jordan Nelson': require('../../images/atom_portraits/Nelson-Jordan.jpg'),
    "Mary O'Neill": require('../../images/atom_portraits/ONeill-Mary.jpg'),
    'Patrick Pale': require('../../images/atom_portraits/Pale-Patrick.jpg'),
    'Nathan Papes': require('../../images/atom_portraits/Papes-Nathan.jpg'),
    'Tammy Pearson': require('../../images/atom_portraits/Pearson-Tammy.jpg'),
    'Andy Peterson': require('../../images/atom_portraits/Peterson-Andy.jpg'),
    'Jason Porritt': require('../../images/atom_portraits/Porritt-Jason.jpg'),
    'Viviana Rosas Romero': require('../../images/atom_portraits/Rosas-Viviana.jpg'),
    'John Ruble': require('../../images/atom_portraits/Ruble-John.jpg'),
    'Jordan Schaenzle': require('../../images/atom_portraits/Schaenzle-Jordan.jpg'),
    'Sivhaun Sera': require('../../images/atom_portraits/Sera-Sivhaun.jpg'),
    'Doug Shipp': require('../../images/atom_portraits/Shipp-Doug.jpg'),
    'Jake Silas': require('../../images/atom_portraits/Silas-Jake.jpg'),
    'Matt Soto': require('../../images/atom_portraits/Soto-Matt.jpg'),
    'Ty Swanson': require('../../images/atom_portraits/Swanson-Tyler.jpg'),
    'Michael Swieton': require('../../images/atom_portraits/Swieton-Mike.jpg'),
    'Sam Tahiri': require('../../images/atom_portraits/Tahiri-Sam.jpg'),
    'Taylor Vanden Hoek': require('../../images/atom_portraits/VandenHoek-Taylor.jpg'),
    'Gage Vander Clay': require('../../images/atom_portraits/VanderClay-Gage.jpg'),
    'Brian Vanderwal': require('../../images/atom_portraits/Vanderwal-Brian.jpg'),
    'Terri Vruggink': require('../../images/atom_portraits/Vruggink-Terri.jpg'),
    'Patrick Warren': require('../../images/atom_portraits/Warren-Patrick.jpg'),
    'Jeff Williams': require('../../images/atom_portraits/Williams-Jeff.jpg'),
    'Alex Zurek': require('../../images/atom_portraits/Zurek-Alex.jpg'),
  },
];

export const atomicPeople = [
  {
    id: 0,
    name: atomic_people[0],
    isChecked: false,
  },
  {
    id: 1,
    name: atomic_people[1],
    isChecked: false,
  },
  {
    id: 2,
    name: atomic_people[2],
    isChecked: false,
  },
  {
    id: 3,
    name: atomic_people[3],
    isChecked: false,
  },
  {
    id: 4,
    name: atomic_people[4],
    isChecked: false,
  },
  {
    id: 5,
    name: atomic_people[5],
    isChecked: false,
  },
  {
    id: 6,
    name: atomic_people[6],
    isChecked: false,
  },
  {
    id: 7,
    name: atomic_people[7],
    isChecked: false,
  },
  {
    id: 8,
    name: atomic_people[8],
    isChecked: false,
  },
  {
    id: 9,
    name: atomic_people[9],
    isChecked: false,
  },
  {
    id: 10,
    name: atomic_people[10],
    isChecked: false,
  },
  {
    id: 11,
    name: atomic_people[11],
    isChecked: false,
  },
  {
    id: 12,
    name: atomic_people[12],
    isChecked: false,
  },
  {
    id: 13,
    name: atomic_people[13],
    isChecked: false,
  },
  {
    id: 14,
    name: atomic_people[14],
    isChecked: false,
  },
  {
    id: 15,
    name: atomic_people[15],
    isChecked: false,
  },
  {
    id: 16,
    name: atomic_people[16],
    isChecked: false,
  },
  {
    id: 17,
    name: atomic_people[17],
    isChecked: false,
  },
  {
    id: 18,
    name: atomic_people[18],
    isChecked: false,
  },
  {
    id: 19,
    name: atomic_people[19],
    isChecked: false,
  },
  {
    id: 20,
    name: atomic_people[20],
    isChecked: false,
  },
  {
    id: 21,
    name: atomic_people[21],
    isChecked: false,
  },
  {
    id: 22,
    name: atomic_people[22],
    isChecked: false,
  },
  {
    id: 23,
    name: atomic_people[23],
    isChecked: false,
  },
  {
    id: 24,
    name: atomic_people[24],
    isChecked: false,
  },
  {
    id: 25,
    name: atomic_people[25],
    isChecked: false,
  },
  {
    id: 26,
    name: atomic_people[26],
    isChecked: false,
  },
  {
    id: 27,
    name: atomic_people[27],
    isChecked: false,
  },
  {
    id: 28,
    name: atomic_people[28],
    isChecked: false,
  },
  {
    id: 29,
    name: atomic_people[29],
    isChecked: false,
  },
  {
    id: 30,
    name: atomic_people[30],
    isChecked: false,
  },
  {
    id: 31,
    name: atomic_people[31],
    isChecked: false,
  },
  {
    id: 32,
    name: atomic_people[32],
    isChecked: false,
  },
  {
    id: 33,
    name: atomic_people[33],
    isChecked: false,
  },
  {
    id: 34,
    name: atomic_people[34],
    isChecked: false,
  },
  {
    id: 35,
    name: atomic_people[35],
    isChecked: false,
  },
  {
    id: 36,
    name: atomic_people[36],
    isChecked: false,
  },
  {
    id: 37,
    name: atomic_people[37],
    isChecked: false,
  },
  {
    id: 38,
    name: atomic_people[38],
    isChecked: false,
  },
  {
    id: 39,
    name: atomic_people[39],
    isChecked: false,
  },
  {
    id: 40,
    name: atomic_people[40],
    isChecked: false,
  },
  {
    id: 41,
    name: atomic_people[41],
    isChecked: false,
  },
  {
    id: 42,
    name: atomic_people[42],
    isChecked: false,
  },
  {
    id: 43,
    name: atomic_people[43],
    isChecked: false,
  },
  {
    id: 44,
    name: atomic_people[44],
    isChecked: false,
  },
  {
    id: 45,
    name: atomic_people[45],
    isChecked: false,
  },
  {
    id: 46,
    name: atomic_people[46],
    isChecked: false,
  },
  {
    id: 47,
    name: atomic_people[47],
    isChecked: false,
  },
  {
    id: 48,
    name: atomic_people[48],
    isChecked: false,
  },
  {
    id: 49,
    name: atomic_people[49],
    isChecked: false,
  },
  {
    id: 50,
    name: atomic_people[50],
    isChecked: false,
  },
  {
    id: 51,
    name: atomic_people[51],
    isChecked: false,
  },
  {
    id: 52,
    name: atomic_people[52],
    isChecked: false,
  },
  {
    id: 53,
    name: atomic_people[53],
    isChecked: false,
  },
  {
    id: 54,
    name: atomic_people[54],
    isChecked: false,
  },
  {
    id: 55,
    name: atomic_people[55],
    isChecked: false,
  },
  {
    id: 56,
    name: atomic_people[56],
    isChecked: false,
  },
  {
    id: 57,
    name: atomic_people[57],
    isChecked: false,
  },
  {
    id: 58,
    name: atomic_people[58],
    isChecked: false,
  },
  {
    id: 59,
    name: atomic_people[59],
    isChecked: false,
  },
  {
    id: 60,
    name: atomic_people[60],
    isChecked: false,
  },
  {
    id: 61,
    name: atomic_people[61],
    isChecked: false,
  },
  {
    id: 62,
    name: atomic_people[62],
    isChecked: false,
  },
  {
    id: 63,
    name: atomic_people[63],
    isChecked: false,
  },
  {
    id: 64,
    name: atomic_people[64],
    isChecked: false,
  },
  {
    id: 65,
    name: atomic_people[65],
    isChecked: false,
  },
  {
    id: 66,
    name: atomic_people[66],
    isChecked: false,
  },
  {
    id: 67,
    name: atomic_people[67],
    isChecked: false,
  },
  {
    id: 68,
    name: atomic_people[68],
    isChecked: false,
  },
  {
    id: 69,
    name: atomic_people[69],
    isChecked: false,
  },
  {
    id: 70,
    name: atomic_people[70],
    isChecked: false,
  },
  {
    id: 71,
    name: atomic_people[71],
    isChecked: false,
  },
  {
    id: 72,
    name: atomic_people[72],
    isChecked: false,
  },
  {
    id: 73,
    name: atomic_people[73],
    isChecked: false,
  },
  {
    id: 74,
    name: atomic_people[74],
    isChecked: false,
  },
  {
    id: 75,
    name: atomic_people[75],
    isChecked: false,
  },
  {
    id: 76,
    name: atomic_people[76],
    isChecked: false,
  },
  {
    id: 77,
    name: atomic_people[77],
    isChecked: false,
  },
  {
    id: 78,
    name: atomic_people[78],
    isChecked: false,
  },
  {
    id: 79,
    name: atomic_people[79],
    isChecked: false,
  },
  {
    id: 80,
    name: atomic_people[80],
    isChecked: false,
  },
  {
    id: 81,
    name: atomic_people[81],
    isChecked: false,
  },
];

export const atomic_people_sorted = atomicPeople.sort((a, b) =>
  a.name > b.name ? 1 : -1,
);

export const atomicDirectory = [
  {
    title: 'A',
    data: [
      atomic_people_sorted[0].name,
      atomic_people_sorted[1].name,
      atomic_people_sorted[2].name,
      atomic_people_sorted[3].name,
      atomic_people_sorted[4].name,
    ],
  },
  {
    title: 'B',
    data: [
      atomic_people_sorted[5].name,
      atomic_people_sorted[6].name,
      atomic_people_sorted[7].name,
      atomic_people_sorted[8].name,
    ],
  },
  {
    title: 'C',
    data: [
      atomic_people_sorted[9].name,
      atomic_people_sorted[10].name,
      atomic_people_sorted[11].name,
    ],
  },
  {
    title: 'D',
    data: [
      atomic_people_sorted[12].name,
      atomic_people_sorted[13].name,
      atomic_people_sorted[14].name,
      atomic_people_sorted[15].name,
      atomic_people_sorted[16].name,
    ],
  },
  {
    title: 'E',
    data: [atomic_people_sorted[17].name],
  },
  {
    title: 'G',
    data: [atomic_people_sorted[18].name, atomic_people_sorted[19].name],
  },
  {
    title: 'J',
    data: [
      atomic_people_sorted[20].name,
      atomic_people_sorted[21].name,
      atomic_people_sorted[22].name,
      atomic_people_sorted[23].name,
      atomic_people_sorted[24].name,
      atomic_people_sorted[25].name,
      atomic_people_sorted[26].name,
      atomic_people_sorted[27].name,
      atomic_people_sorted[28].name,
      atomic_people_sorted[29].name,
      atomic_people_sorted[30].name,
      atomic_people_sorted[31].name,
      atomic_people_sorted[32].name,
      atomic_people_sorted[33].name,
      atomic_people_sorted[34].name,
    ],
  },
  {
    title: 'K',
    data: [
      atomic_people_sorted[35].name,
      atomic_people_sorted[36].name,
      atomic_people_sorted[37].name,
      atomic_people_sorted[38].name,
      atomic_people_sorted[39].name,
      atomic_people_sorted[40].name,
      atomic_people_sorted[41].name,
    ],
  },
  {
    title: 'L',
    data: [
      atomic_people_sorted[42].name,
      atomic_people_sorted[43].name,
      atomic_people_sorted[44].name,
      atomic_people_sorted[45].name,
    ],
  },
  {
    title: 'M',
    data: [
      atomic_people_sorted[46].name,
      atomic_people_sorted[47].name,
      atomic_people_sorted[48].name,
      atomic_people_sorted[49].name,
      atomic_people_sorted[50].name,
      atomic_people_sorted[51].name,
      atomic_people_sorted[52].name,
      atomic_people_sorted[53].name,
      atomic_people_sorted[54].name,
      atomic_people_sorted[55].name,
    ],
  },
  {
    title: 'N',
    data: [
      atomic_people_sorted[56].name,
      atomic_people_sorted[57].name,
      atomic_people_sorted[58].name,
      atomic_people_sorted[59].name,
      atomic_people_sorted[60].name,
    ],
  },
  {
    title: 'P',
    data: [
      atomic_people_sorted[61].name,
      atomic_people_sorted[62].name,
      atomic_people_sorted[63].name,
      atomic_people_sorted[64].name,
    ],
  },
  {
    title: 'R',
    data: [
      atomic_people_sorted[65].name,
      atomic_people_sorted[66].name,
      atomic_people_sorted[67].name,
      atomic_people_sorted[68].name,
    ],
  },
  {
    title: 'S',
    data: [
      atomic_people_sorted[69].name,
      atomic_people_sorted[70].name,
      atomic_people_sorted[71].name,
      atomic_people_sorted[72].name,
      atomic_people_sorted[73].name,
    ],
  },
  {
    title: 'T',
    data: [
      atomic_people_sorted[74].name,
      atomic_people_sorted[75].name,
      atomic_people_sorted[76].name,
      atomic_people_sorted[77].name,
    ],
  },
  {
    title: 'V',
    data: [atomic_people_sorted[78].name, atomic_people_sorted[79].name],
  },
  {
    title: 'W',
    data: [atomic_people_sorted[80].name],
  },
  {
    title: 'Z',
    data: [atomic_people_sorted[81].name],
  },
];
